workflows:
  native-android:
    name: Z Translate Build
    max_build_duration: 30
    environment:
      java: 17
    triggering:
      events:
        - push
    scripts:
      - name: Build Android APK
        script: |
          # We bypass the missing wrapper and use the server's Gradle directly
          # This is the safest way for mobile-only developers
          gradle assembleDebug
    artifacts:
      - app/build/outputs/apk/**/*.apk
    publishing:
      email:
        recipients:
          - funpasscloud518@gmail.com
