workflows:
  native-android:
    name: Z Translate Build
    max_build_duration: 30
    environment:
      # Removed 'android_sdk' as it is handled automatically by Codemagic
      java: 17
    triggering:
      events:
        - push
        scripts:
      - name: Build Android APK
        script: |
          # Use system gradle instead of the missing wrapper
          gradle assembleDebug
      - name: Generate Wrapper and Build
        script: |
          gradle wrapper --gradle-version 8.1.1
          chmod +x gradlew
          ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/apk/**/*.apk
    publishing:
      email:
        recipients:
          - funpasscloud518@gmail.com
