workflows:
  native-android:
    name: Z Translate Build
    max_build_duration: 30
    environment:
      java: 17
    triggering:
      events:
        - push
    # The 'scripts' section must be at the same level as 'triggering'
    scripts:
      - name: Build Android APK
        script: |
          # Check if gradlew exists, if not, use system gradle
          if [ -f "gradlew" ]; then
            chmod +x gradlew
            ./gradlew assembleDebug
          else
            echo "Gradle wrapper not found, using system gradle..."
            gradle assembleDebug
          fi
    artifacts:
      - app/build/outputs/apk/**/*.apk
    publishing:
      email:
        recipients:
          - funpasscloud518@gmail.com
