workflows:
  native-android:
    name: Z Translate Build
    max_build_duration: 30
    environment:
      android_sdk: 34
      java: 17
    triggering:
      events:
        - push
    scripts:
      - name: Build Android APK
        script: |
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
